apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: akash
  name: first-deployment
  labels:
    app: akash-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akash-1
  template:
    metadata:
      labels:
        app: akash-1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80