apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: akash
  name: first-deployment
  labels:
    app: akash-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akash-1
  template:
    metadata:
      labels:
        app: akash-1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

## Steps to create Deployment ##
1 Install Kubectl eksctl
2 Create cluster
3 Create manifest file for deployment
  vi deployment.yml

4 Create deployment using command

  kubectl apply -f deployment.yml

5 To check created deployment

  kubectl get deployment
  kubectl get deploy