apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-access
  namespace: default
subjects:
- kind: ServiceAccount
  name: akash-sa
  namespace: default
roleRef:
  kind: Role
  name: my-first-role
  apiGroup: rbac.authorization.k8s.io